detection:
  model_path: "models/best.pt"
  conf_threshold: 0.4
  iou_threshold: 0.45
  device: "auto"
  max_det: 50
  classes: [1, 2, 3]

tracking:
  tracker_type: "advanced_reid"  
  persist: true
  track_high_thresh: 0.5  
  track_low_thresh: 0.1
  new_track_thresh: 0.5
  track_buffer: 30
  match_thresh: 0.8
  proximity_thresh: 0.5
  appearance_thresh: 0.3  

advanced_reid:
  enabled: true
  feature_extractor: "lightweight"  
  feature_dim: 512
  part_based: true
  parts: ["head", "torso_upper", "torso_lower", "legs", "feet"]
  
  deep_features:
    backbone: "resnet50"
    pretrained: true
    frozen_layers: 2  
    dropout: 0.2
    
  gallery:
    enabled: true
    max_size: 100  
    update_frequency: 10
    similarity_threshold: 0.6
    temporal_decay: 0.95
    confidence_threshold: 0.7
    
  matching:
    use_multiple_metrics: true
    weights:
      appearance: 0.5
      pose: 0.2
      color: 0.2
      motion: 0.1
    distance_metric: "cosine"
    
  jersey_ocr:
    enabled: false
    confidence_threshold: 0.6
    preprocessing: true
    number_weight: 0.3

simple_reid:
  enabled: true
  feature_dim: 512  
  gallery_size: 30
  similarity_threshold: 0.6  
  update_frequency: 10
  temporal_window: 30  

team_classification:
  enabled: true
  method: "color_clustering"
  n_clusters: 2
  confidence_threshold: 0.6
  color_regions: ["jersey_top"]

pose_estimation:
  enabled: false
  model: "lightweight"  
  keypoints: 17
  confidence_threshold: 0.3

visualization:
  show_trails: false
  show_ids: true
  show_confidence: true
  show_team_colors: true
  show_reid_info: true
  show_jersey_numbers: true
  show_pose_keypoints: false
  bbox_thickness: 2
  font_scale: 0.6

video:
  input_path: "data/input/15sec_input_720p.mp4"
  output_path: "outputs/videos/demo_advanced_output.mp4"  
  fps: 30

debug:
  verbose: false
  log_level: "INFO"
